---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/consoles":
    get:
      summary: Retrieves all consoles
      tags:
      - Consoles
      parameters:
      - name: Authorization
        in: header
        schema:
          type: string
      responses:
        '200':
          description: consoles found
  "/api/v1/consoles/{id}":
    get:
      summary: Retrieves a console
      tags:
      - Consoles
      parameters:
      - name: Authorization
        in: header
        schema:
          type: string
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: console found
        '404':
          description: console not found
    post:
      summary: Create a new console
      tags:
      - Console
      parameters: []
      responses:
        '200':
          description: console created successfully
          content:
            application/json:
              examples:
                example_0:
                  value:
                    status: Success
                    message: console created successfully
                    data:
                      id: 1
                      name: NSWICTH
                      photo: image_url
                      purchase_price: 10000
                      rental_price: 100
                      description: Learn about Nintendo Switch Lite. It is compact, lightweight, and dedicated to handheld play. Making it perfect for gamers on the move.
              schema:
                type: object
                properties:
                  status:
                    type: string
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                      name:
                        type: string
                      photo:
                        type: string
                      purchase_price:
                        type: number
                      rental_price:
                        type: number
                      description:
                        type: string
                    required:
                    - id
                    - name
                    - photo
                    - purchase_price
                    - rental_price
                    - description
                required:
                - status
                - message
                - data
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                photo:
                  type: string
                purchase_price:
                  type: number
                rental_price:
                  type: number
                description:
                  type: string
              required:
              - name
              - photo
              - purchase_price
              - rental_price
              - description
    delete:
      summary: Delete a specific console
      tags:
      - Console
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: Console deleted successfully
          content:
            application/json:
              examples:
                example_0:
                  value:
                    status: Success
                    message: Console deleted successfully
                    data:
                      id: 1
                      name: NSWICTH
                      photo: image_url
                      purchase_price: 10000
                      rental_price: 100
                      description: Learn about Nintendo Switch Lite. It is compact, lightweight, and dedicated to handheld play. Making it perfect for gamers on the move.
              schema:
                type: object
                properties:
                  status:
                    type: string
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                      name:
                        type: string
                      photo:
                        type: string
                      purchase_price:
                        type: number
                      rental_price:
                        type: number
                      description:
                        type: string
                    required:
                    - id
                    - name
                    - photo
                    - purchase_price
                    - rental_price
                    - description
                required:
                - status
                - message
                - data
  "/api/v1/reservations":
    post:
      summary: create a reservation
      tags:
      - Reservations
      parameters:
      - name: user_id
        in: path
        required: true
        schema:
          type: string
      - name: Authorization
        in: header
        schema:
          type: string
      responses:
        '201':
          description: reservation created
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: integer
                city:
                  type: string
                reserve_date:
                  type: string
                console_id:
                  type: integer
              required:
              - user_id
              - city
              - reserve_date
              - console_id
    get:
      summary: Fetch reservations for a user
      tags:
      - Reservations
      parameters:
      - name: user_id
        in: path
        required: true
        schema:
          type: string
      - name: Authorization
        in: header
        schema:
          type: string
      responses:
        '200':
          description: reservations found
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    user_id:
                      type: integer
                    city:
                      type: string
                    reserve_date:
                      type: string
                    console_id:
                      type: integer
                  required:
                  - id
                  - user_id
                  - city
                  - reserve_date
                  - console_id
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
