---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/consoles":
    post:
      summary: Creates a console
      tags:
      - Consoles
      parameters:
      - name: Authorization
        in: header
        schema:
          type: string
      responses:
        '200':
          description: console created
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                purchase_price:
                  type: number
                rental_price:
                  type: number
                description:
                  type: string
                photo:
                  type: string
              required:
              - name
              - purchase_price
              - rental_price
              - description
              - photo
    get:
      summary: Retrieves all consoles
      tags:
      - Consoles
      parameters:
      - name: Authorization
        in: header
        schema:
          type: string
      responses:
        '200':
          description: consoles found
  "/api/v1/consoles/{id}":
    delete:
      summary: Deletes a console
      tags:
      - Consoles
      parameters:
      - name: Authorization
        in: header
        schema:
          type: string
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: console deleted
        '404':
          description: console not found
    get:
      summary: Retrieves a console
      tags:
      - Consoles
      parameters:
      - name: Authorization
        in: header
        schema:
          type: string
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: console found
        '404':
          description: console not found
  "/api/v1/reservations":
    post:
      summary: create a reservation
      tags:
      - Reservations
      parameters:
      - name: user_id
        in: path
        required: true
        schema:
          type: string
      - name: Authorization
        in: header
        schema:
          type: string
      responses:
        '201':
          description: reservation created
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: integer
                city:
                  type: string
                reserve_date:
                  type: string
                console_id:
                  type: integer
              required:
              - user_id
              - city
              - reserve_date
              - console_id
    get:
      summary: Fetch reservations for a user
      tags:
      - Reservations
      parameters:
      - name: user_id
        in: path
        required: true
        schema:
          type: string
      - name: Authorization
        in: header
        schema:
          type: string
      responses:
        '200':
          description: reservations found
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    user_id:
                      type: integer
                    city:
                      type: string
                    reserve_date:
                      type: string
                    console_id:
                      type: integer
                  required:
                  - id
                  - user_id
                  - city
                  - reserve_date
                  - console_id
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
